# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useman',
            old_name='user_id',
            new_name='user',
        ),
    ]
