# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190421_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseMan',
            new_name='UserMan',
        ),
    ]
