# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='注意事项')),
            ],
            options={
                'verbose_name': '注意事项',
                'verbose_name_plural': '注意事项',
            },
        ),
        migrations.CreateModel(
            name='FeeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='费用说明')),
            ],
            options={
                'verbose_name': '费用说明',
                'verbose_name_plural': '费用说明',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=100, verbose_name='简要说明')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('time', models.IntegerField(verbose_name='花费天数')),
                ('min_price', models.IntegerField(verbose_name='最低价格')),
                ('max_price', models.IntegerField(verbose_name='最高价格')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('route', models.CharField(max_length=50, verbose_name='行程')),
                ('power', models.IntegerField(verbose_name='所需体力')),
                ('click', models.IntegerField(verbose_name='点击数')),
                ('date', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('image', models.ImageField(upload_to='imgae/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '线路',
                'verbose_name_plural': '线路',
            },
        ),
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Route', verbose_name='线路')),
            ],
            options={
                'verbose_name': '线路详情',
                'verbose_name_plural': '线路详情',
            },
        ),
        migrations.CreateModel(
            name='RouteIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='简介')),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.RouteDetails', verbose_name='详情')),
            ],
            options={
                'verbose_name': '线路简介',
                'verbose_name_plural': '线路简介',
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='安排')),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.RouteDetails', verbose_name='详情')),
            ],
            options={
                'verbose_name': '行程安排',
                'verbose_name_plural': '行程安排',
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=20, verbose_name='线路类型')),
            ],
            options={
                'verbose_name': '线路分类',
            },
        ),
        migrations.CreateModel(
            name='TravelTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('team', models.IntegerField(verbose_name='队伍编号')),
                ('status', models.CharField(choices=[('0', '报名'), ('1', '已满')], default='0', max_length=2, verbose_name='队伍状态')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.Route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.RouteType', verbose_name='线路类型'),
        ),
        migrations.AddField(
            model_name='feedescription',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.RouteDetails', verbose_name='详情'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.RouteDetails', verbose_name='详情'),
        ),
    ]
